src/resources/views/errors/403.blade.php

Adding a redirection button to the 403 error page
#208

Issue 208  minor no redirection when landing on you don t have the right to do this

---

src/app/Http/Controllers/ManageUsersController.php
src/app/Http/Requests/StoreRequestRoleRequest.php
src/app/Http/Requests/UpdateUsersRequest.php
src/app/Rules/NotLastMoreImportantRole.php
src/resources/views/livewire/request-role.blade.php
src/resources/views/user/edit.blade.php

Now, you cannot loose your role if you try to change it as the highest permission user
- Closed #213

Issue 213  coussin admin role loss permission

---

src/app/Http/Controllers/ManageUsersController.php
src/app/Http/Requests/StoreRequestRoleRequest.php
src/app/Http/Requests/UpdateUsersRequest.php
src/app/Models/ApiLog.php
src/app/Models/Link.php
src/app/Models/Refugee.php
src/app/Rules/NotLastMoreImportantRole.php
src/app/Rules/NotLastUser.php
src/database/factories/EventFactory.php
src/database/factories/LinkFactory.php
src/database/factories/RefugeeFactory.php
src/database/migrations/2021_04_28_154344_create_api_logs_table.php
src/resources/views/api_logs/index.blade.php
src/resources/views/api_logs/show.blade.php
src/resources/views/user/edit.blade.php
src/resources/views/user/show.blade.php

**Add COUSSIN :** 
a user can't be deleted if : 
- he's the last user
- he's the last admin
Change the rule 'NotLastMoreImportantRole' to be used in several conditions.
Debug : because of the rule application in the validation process, an admin couldn't change another user role.
**Debug APILog view**
Use relationship inside the model
Debug views
- Closed #219

[PR] Issue 219 coussin i should not be able to delete myself in some conditions + APILog

---

src/app/Rules/NotLastMoreImportantRole.php

It solves the issue 229, changing the request validator
- Closed #229

admin cant change his name -> corrected by changing the rule

---

src/app/Http/Controllers/RefugeeController.php

check if value already exists -> if true : update else create
Correct the issue
- Closed #206

[PR] Error EDIT person -> corrected

---

src/app/Http/Controllers/FieldsController.php
src/app/Http/Controllers/LinkController.php
src/app/Http/Controllers/RefugeeController.php
src/app/Http/Requests/StoreLinkApiRequest.php
src/app/Http/Requests/StoreRefugeeApiRequest.php
src/app/Models/Field.php
src/app/Models/ListControl.php
src/app/Models/Refugee.php
src/app/Models/Translation.php
src/database/migrations/jsonDataset/config/lists_controls.json
src/database/migrations/jsonDataset/fields.json
src/database/seeders/FieldSeeder.php
src/database/seeders/GlobalListControlSeeder.php
src/resources/views/fields/edit.blade.php

Adaptation de l'api avec le nouveau format. 
⚠️ Migration is required
getAllFields ok and is based on the id
addPerson works
addRelation works
For now, the server returns the id when a element is created/updated. When the application want to update, it has to precise the id in the request.
- Closed #147

[PR] adaptation de l api

---

src/app/Models/Permission.php
src/app/Policies/GlobalPolicy.php
src/resources/views/user/show.blade.php

Add the ability to manage api token from user
- #245

[PR] Feature/issue 245  new feature allow admin to handle api request from users view

---

src/app/Http/Controllers/FieldsController.php
src/app/Http/Controllers/LinkController.php
src/app/Http/Requests/StoreFieldRequest.php
src/app/Http/Requests/UpdateFieldRequest.php
src/app/Models/Link.php
src/resources/views/links/create.blade.php
src/resources/views/links/index.blade.php
src/resources/views/navigation-menu.blade.php
src/resources/views/person/index.blade.php
src/resources/views/person/show.blade.php
src/routes/web.php

Improve filtering options #222 
Debug API #251 
Fields label no more needs to be unique #201 
Works on addFrom and addTo ⚠️ route changed #98 
#222
#251
#201
#98

[PR] Feature/issue 222  new feature upgrade filtering options

---

.github/workflows/docker-image.yml
Dockerfile
README.md

Main to preprod

---

src/resources/views/links/index.blade.php
src/routes/web.php

Remove duplicate route (links.create)

hot-fix remove duplicate route (links.create)

---

src/app/Console/Commands/makeList.php
src/database/migrations/2021_04_17_212623_create_fields_table.php
src/resources/views/fields/show.blade.php
src/resources/views/navigation-menu.blade.php

Debugs - hotfixes

---

src/app/Http/Controllers/CrewController.php
src/app/Http/Controllers/FieldsController.php
src/app/Http/Controllers/ManageUsersController.php
src/app/Http/Requests/StoreFieldRequest.php
src/app/Http/Requests/StoreUserRequest.php
src/app/Http/Requests/addUserToCrewRequest.php
src/app/Models/Crew.php
src/resources/views/crew/create.blade.php
src/resources/views/crew/index.blade.php
src/resources/views/crew/show.blade.php
src/resources/views/errors/404.blade.php
src/resources/views/fields/create.blade.php
src/resources/views/navigation-menu.blade.php
src/resources/views/roles/create.blade.php
src/resources/views/roles/edit.blade.php
src/resources/views/user/create.blade.php
src/routes/web.php

Fix many things, related in the following issues : 
- #269
- #270 
- #271 
- #272 
- #273 
- #276 
- #277

[PR] Fix several thing regarding the meeting with JP

---

src/app/Http/Controllers/CytoscapeController.php
src/package.json
src/public/js/cytoscape/index.js
src/resources/js/cytoscape/index.js
src/resources/views/cytoscape/index.blade.php
src/resources/views/vendor/jetstream/components/welcome.blade.php

static role coloration
please run `npm run dev` to apply the changes.
#118

static role coloration

---

src/app/Http/Controllers/SourceController.php
src/app/Http/Requests/StoreSourceRequest.php
src/app/Http/Requests/UpdateSourceRequest.php
src/app/Models/ListSourceType.php
src/app/Models/Permission.php
src/app/Models/Source.php
src/app/Policies/SourcePolicy.php
src/database/factories/SourceFactory.php
src/database/migrations/2022_11_03_084914_create_sources_table.php
src/database/migrations/2022_11_03_095042_create_list_source_types_table.php
src/database/migrations/jsonDataset/config/lists_controls.json
src/database/migrations/jsonDataset/listsourcetypes.json
src/database/seeders/DatabaseSeeder.php
src/database/seeders/ListSourceTypeSeeder.php
src/database/seeders/SourceSeeder.php
src/resources/views/event/edit.blade.php
src/resources/views/navigation-menu.blade.php
src/resources/views/sources/create.blade.php
src/resources/views/sources/edit.blade.php
src/resources/views/sources/index.blade.php
src/resources/views/sources/show.blade.php
src/routes/web.php

Add the source concept to the project :
- Resource : CRUD
- Model
- Migration
- Factory
- Policy
- Request
- Seeder
Add to default list
Please run the following : 
```
php artisan migrate
php artisan permission:update
php artisan list:update --seed
```
- Closed #182

[PR] Feature/issue 182 ressource source

---

src/app/Http/Controllers/RefugeeController.php
src/app/Policies/GlobalPolicy.php
src/resources/views/person/create.blade.php
src/resources/views/person/edit.blade.php
src/resources/views/person/show.blade.php

Add a form to quickly add a person as a source.
Debug #293. (details in commit).
- Closed #303 
- Fix #293

[PR] Feature/issue 303  new feature quick add person as a source

---

Dockerfile

Add xdebug

---

.gitignore
src/app/Models/Field.php
src/resources/views/person/create.blade.php

issue: #300
Signed-off-by: mathisfchx <72497356+mathisfchx@users.noreply.github.com>
Spinner Java type to be automatic when selecting List type during the creation of the fied

[PR] fix(field): Spinner Java type

---

src/app/Http/Controllers/FieldsController.php
src/app/Models/Event.php
src/app/Models/Field.php
src/app/Models/Source.php

issue: #322 
Signed-off-by: mathisfchx <72497356+mathisfchx@users.noreply.github.com>
Edit a list type field was not possible

[PR] fix(field): Spinner Java type (edit field)

---

src/app/Http/Controllers/LinkController.php
src/app/Models/Crew.php
src/app/Models/Link.php
src/routes/api.php
src/tests/Feature/Event.php
src/tests/Feature/LinkTest.php
src/tests/Feature/PersonTest.php
src/tests/TestCase.php

Add api relations -> get
Fix :
- #315

[PR] Feature/issue 315  new feature new api feature link

---

src/app/Http/Controllers/LinkController.php
src/app/Http/Requests/StoreLinkRequest.php
src/app/Http/Requests/UpdateLinkRequest.php
src/app/Models/Link.php
src/resources/views/crew/edit.blade.php
src/resources/views/event/create.blade.php
src/resources/views/event/edit.blade.php
src/resources/views/fields/create.blade.php
src/resources/views/fields/edit.blade.php
src/resources/views/links/create.blade.php
src/resources/views/links/edit.blade.php
src/resources/views/links/index.blade.php
src/resources/views/lists_control/create.blade.php
src/resources/views/lists_control/edit.blade.php
src/resources/views/person/create.blade.php
src/resources/views/person/edit.blade.php
src/resources/views/roles/edit.blade.php
src/resources/views/sources/create.blade.php
src/resources/views/sources/edit.blade.php
src/resources/views/user/edit.blade.php

Add date to relations
Rename Edit to Save
Fix :
- #326 
- #327

[PR] Rename Edit -> Save + relations with date

---

src/app/Http/Controllers/CytoscapeController.php

Error while checking the exsitance of role in cytoscape controller
issue: #342
Macro description of the PR
Fix :
- #

hotfix(cytoscape): Cytoscape 500 errror

---

src/app/Http/Controllers/ListControlController.php
src/app/Policies/RefugeePolicy.php
src/routes/api.php

Add API get list feature.
Fix :
- #314 
- #353

Feature/issue 314  new feature new api feature list

---

src/app/Http/Controllers/LinkController.php
src/app/Http/Requests/StoreLinkApiRequest.php
src/app/Models/Link.php
src/app/Models/Refugee.php
src/database/migrations/2022_12_02_082757_create_list_relation_types_table.php
src/database/migrations/jsonDataset/config/lists_controls.json
src/database/migrations/jsonDataset/fields.json
src/database/migrations/jsonDataset/listdatatypes.json
src/database/migrations/jsonDataset/listrelationtypes.json
src/resources/views/lists_control/show.blade.php

- Add label 'type' to relation type
- BDV can displays list displayed value
- Displayed value is displayed in list (when the field is associated to a list)
- Debug the relation API
Fix :
- #366 
- #367 
- #348

[PR] Feature/issue 366  new feature add a label column on relation type

---

src/app/Console/Commands/DeleteOldZipFiles.php
src/app/Console/Kernel.php
src/app/Http/Controllers/CrewController.php
src/app/Http/Livewire/GdprActions.php
src/composer.json
src/database/migrations/jsonDataset/fields.json
src/resources/markdown/policy.md
src/resources/views/livewire/gdpr-actions.blade.php
src/resources/views/person/index.blade.php
src/resources/views/profile/show.blade.php
src/resources/views/profile/two-factor-authentication-form.blade.php

Add GDPR feature : 
- auto add a required checkbox (user consent)
- Search and delete all person related information's
+ debug the dev person.index
```
composer update
php artisan migrate:refresh --seed
npm run prod
```
Also add the following in the crontable (crontab -e)
```
* * * * * cd /var/www/html && php artisan schedule:run >> /dev/null 2>&1
```
Fix :
- #376

[PR] Feature/issue 376  new feature gdpr friendly

---

src/resources/views/navigation-menu.blade.php
src/resources/views/sources/show.blade.php

(+ duplicate button on source show)
issue: #391, #392
Signed-off-by: mathisfchx <72497356+mathisfchx@users.noreply.github.com>

[PR] fix(nav-bar): update

---

src/resources/views/sources/edit.blade.php

Fixed bug when editing source.
Fix :
- #
ø

[PR] Fix source bug

---

src/resources/views/sources/edit.blade.php

calling unkwown class, fixed it
Fix :
- #402

[PR] BUG: calling unkwown class, fixed it

---

src/resources/views/cytoscape/index.blade.php
src/resources/views/duplicate/index.blade.php
src/resources/views/fields/create.blade.php
src/resources/views/fields/edit.blade.php
src/resources/views/links/create.blade.php
src/resources/views/livewire/gdpr-actions.blade.php
src/resources/views/navigation-menu.blade.php
src/resources/views/person/create.blade.php
src/resources/views/person/create_from_json.blade.php
src/resources/views/person/index.blade.php
src/resources/views/person/show.blade.php

issue: #406
Change the naming of Persons to Items (more global meaning)
-> I've just changed the prompts, not the routes and name of the variables, should I ?

[PR] fix(naming): persons->items

---

src/app/Http/Controllers/CytoscapeController.php
src/resources/views/cytoscape/index.blade.php

network graph's legend now only show used relation types

[PR] Feature/issue 408 : network graph's legend to only show used relation types

---

src/app/Http/Controllers/FieldsController.php

Showing the field's importance when showing it's details => now it works

[PR] fix(show): fields importance

---

src/resources/views/links/index.blade.php
src/resources/views/person/index.blade.php

[PR] fix(search): index items and relations

---

README.md
src/composer.json
src/phpunit.xml
src/tests/Feature/PersonTest.php

Update composer to use SAIL
Fix :
- #

Issue 437  refactor use laravel sail

---

.github/workflows/gpt_issue.yml

[PR] add got issue
